### ISSUE TITLE
Upgrading from Scanamo v0.9.5 to v1.0.0-M[2|3] can break compilation with a nebulous error message

### ISSUE THREAD

**Issue by rtyley** [scanamo/scanamo#171]
When upgrading from Scanamo v0.9.5 to v1.0.0-M[2|3], I got this compilation error:

```
could not find implicit value for evidence parameter of type com.gu.scanamo.DynamoFormat[ophan.model.CAPIContent]
```

While investigating, I stripped this down to a fairly minimal repo: you can see [the upgrade commit](https://github.com/guardian/ophan-scanamo-upgrade-problem/compare/560ff7a6a90f...18c68829240d) and [resulting build failure](https://travis-ci.org/guardian/ophan-scanamo-upgrade-problem/builds/309003188).

It turned out that [removing an empty case class](https://github.com/guardian/ophan-scanamo-upgrade-problem/commit/aa76ed494b94b648d72ec4156c7c1a1b8bec8dfa) (`CAPIPodcast()`) that `ophan.model.CAPIContent` had as a field fixed the problem, but finding that problem was a bit hit-and-miss because the error message didn't mention `CAPIPodcast` at all :( I guess the error message problem may be related to https://github.com/scanamo/scanamo/pull/85 , and the empty case class restriction related to https://github.com/scanamo/scanamo/pull/140 ?

I couldn't find any release notes that warned about this problem with upgrading, and http://www.scanamo.org/dynamo-format.html doesn't warn about the problem with empty case classes, so, er, I guess this issue serves as some documentation :)

cc @mchv

**Comment by philwills** [comment]
You're diagnosis is correct and I think those are both sensible changes. The empty case class should have thrown a compilation warning, but I would love to have more useful compilation errors and at the least, documentation could be improved.

**Comment by sejsworld** [comment]
We have the same issues, our  project compile fails 2/3 times and without any changes it possible works. This make it almost impossible to work with, since sbt ~compile is not working due to the error. Any ideas of why this happens and how to workaround or fix our model or code to not have this error.
Thanx in advance
Steffen

**Comment by sejsworld** [comment]
I have now removed attributes which where based on these enums and it may be root for the issue

 sealed trait DataTypeEnum
  case object WellnessDaily extends DataTypeEnum
  case object ActivitySummary extends DataTypeEnum
  case object ActivityDetail extends DataTypeEnum
  case object NotSelected extends DataTypeEnum

**Comment by philwills** [comment]
@sejsworld #138 showed that there was potential for data being written incorrectly with the old method, so the derivation got a bit stricter about what types it would derive a type class for in #140. If everything is a case object extending a trait and you always tell Scanamo to treat those values as being the type of that trait, you should be OK.
